#!/bin/bash

# install gems
$gem install rake -v "0.8.2" --no-rdoc --no-ri --bindir=$bin_dir
$gem install sqlite3-ruby -v "1.2.2"  --no-rdoc --no-ri --bindir=$bin_dir
$gem install statarray -v "0.0.1" --no-rdoc --no-ri --bindir=$bin_dir
$gem install haml -v "2.0.3" --no-rdoc --no-ri --bindir=$bin_dir
$gem install thin -v "0.8.2" --no-rdoc --no-ri --bindir=$bin_dir
$gem install rjb -v "1.1.6"  --no-rdoc --no-ri --bindir=$bindir
$gem install rsruby -v "0.5"  -- --with-R-dir=$R_HOME --no-rdoc --no-ri --bindir=$bindir
