#!/bin/bash

# external plugins
mkdir -p $plugin_dir
cd $plugin_dir
git_init $git_url/engines.git engines #2.1.0 # stay at master to fix Dependencies is not a module (TypeError) 
git_init $git_url/active_scaffold.git active_scaffold
git_init $git_url/file_column.git file_column
git_init $git_url/exception_notification.git exception_notification
cd $app_dir

# create haml plugin
vendor/bin/haml --rails .
