#!/bin/bash

# external plugins
mkdir -p $plugin_dir
cd $plugin_dir
git_init git://github.com/lazyatom/engines.git engines
git_init $git_url/active_scaffold.git active_scaffold
git_init $git_url/file_column.git file_column
git_init $git_url/exception_notification.git exception_notification
cd $app_dir

# create haml plugin
haml --rails .

