#!/bin/bash
#===============================================================================
#
#          FILE:  install
# 
#         USAGE:  ./install
# 
#   DESCRIPTION:  installs/updates an OpenTox application
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  helma@in-silico.de, 
#       COMPANY: in silico toxicology 
#       VERSION:  1.0
#       CREATED:  08/27/2008 10:25:01 AM CEST
#      REVISION:  ---
#===============================================================================

source script/variables

mkdir -p $bin_dir
mkdir -p $plugin_dir

source script/install/dependencies
source script/java-home
source script/install/ruby
source script/install/rubygems
source script/install/rails
source script/install/R
source script/install/openbabel
source script/install/gems
source script/install/plugins

$rake app:install

