#!/bin/bash
#===============================================================================
#
#          FILE:  install
# 
#         USAGE:  ./install
# 
#   DESCRIPTION:  installs/updates an OpenTox application
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  helma@in-silico.de, 
#       COMPANY: in silico toxicology 
#       VERSION:  1.0
#       CREATED:  08/27/2008 10:25:01 AM CEST
#      REVISION:  ---
#===============================================================================

git pull

source script/variables

$ruby config/java.rb

source script/upgrade/ruby
source script/upgrade/rubygems
source script/upgrade/rails
source script/upgrade/R
source script/upgrade/openbabel
source script/upgrade/gems
source script/upgrade/plugins

$rake app:upgrade
