#!/bin/bash
#===============================================================================
#
#          FILE:  install
# 
#         USAGE:  ./install
# 
#   DESCRIPTION:  installs/updates an OpenTox application
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  helma@in-silico.de, 
#       COMPANY: in silico toxicology 
#       VERSION:  1.0
#       CREATED:  08/27/2008 10:25:01 AM CEST
#      REVISION:  ---
#===============================================================================


git_url=http://opentox.org/git/ch

app_dir=`pwd`
prefix=$app_dir/vendor
bin_dir=$prefix/bin
src_dir=$prefix/src
gem_dir=$prefix/gems
plugin_dir=$prefix/plugins
r_home=$prefix/R

export PATH=$PATH:$bin_dir
export R_HOME=$r_home
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$R_HOME/bin
export GEM_HOME=$prefix/lib/ruby/gems/1.8
export RUBY=$ruby

# guess JAVA_HOME
if [ ! $JAVA_HOME ]
then
	export JAVA_HOME=`locate -r ".*jvm/.*/bin/java$"|sed 's/\/bin\/java//'|grep -v jre`
fi

# if locate db does not exist
if [ ! $JAVA_HOME ]
then
	export JAVA_HOME=`find / -wholename "/*/jvm/*/bin/java" 2>/dev/null|sed 's/\/bin\/java//'|grep -v jre`
fi

if [ ! $JAVA_HOME ]
then
	echo "Could not find a home directory of your Java installation. Please install Java and set the JAVA_HOME variable."
	exit
fi

sed "2cENV['JAVA_HOME'] = '$JAVA_HOME'" config/java.rb

ruby=$bin_dir/ruby
gem=$bin_dir/gem
r_program=$bin_dir/R
rake=$bin_dir/rake

mkdir -p $bin_dir
mkdir -p $plugin_dir

function git_init {
	dir=`pwd`
	if [ ! -d $2 ]
	then
		git clone $1 $2
	fi
	cd $2
	git pull
	if [ $3 ]
	then
		git checkout $3
	fi
	cd $dir
}

#source script/installation/dependencies
#source script/installation/ruby
#source script/installation/rubygems
source script/installation/rails
#source script/installation/R
#source script/installation/openbabel
#source script/installation/gems
#source script/installation/plugins

$rake app:install

